### ISSUE TITLE
LICENSE file missing

### ISSUE THREAD

**Issue by tomchop** [lucasjones/reggen#2]
How is this code licensed? Care to add a LICENSE.md (or a note in the README) the world can know how we can use it? Thanks! :)

**Comment by corgrath** [comment]
I took the liberty to add a MIT Pull Request for this project, if MIT is okay.

By adding an open source license, other developers don't need to worry about how it may or may not be used =)

https://github.com/lucasjones/reggen/pull/3

**Comment by tomchop** [comment]
That's great, thanks!

**Comment by lucasjones** [comment]
Hi, sorry I didn't see this sooner. I've merged the pull request now so the licensing is clear :)
